---
- name: Create assets directory
  file:
    path: "{{ docker_compose_dir }}/assets"
    state: directory

- name: Copy specified header logo.
  copy:
    src: "{{ customized_assets.header }}"
    dest: "{{ docker_compose_dir }}/assets/logo-header.svg"
  when: customized_assets.header is defined

- name: Copy specified login logo.
  copy:
    src: "{{ customized_assets.login }}"
    dest: "{{ docker_compose_dir }}/assets/logo-login.svg"
  when: customized_assets.login is defined

- name: Copy specified favicon.
  copy:
    src: "{{ customized_assets.favicon }}"
    dest: "{{ docker_compose_dir }}/assets/favicon.ico"
  when: customized_assets.favicon is defined
