---
- name: Create {{ docker_compose_dir }} directory
  file:
    path: "{{ docker_compose_dir }}"
    state: directory

- name: Copy ssl key
  copy:
    src: "{{ ssl_key_path }}"
    dest: "{{ docker_compose_dir }}/{{ ssl_certificate_key }}"
  when: ssl_key_path is defined
  notify:
    - update ca
    - restart container

- name: Copy ssl cert
  copy:
    src: "{{ ssl_certificate_path }}"
    dest: "{{ docker_compose_dir }}/{{ ssl_certificate_cert }}"
  when: ssl_certificate_path is defined
  notify:
    - update ca
    - restart container

- name: Create Docker Compose Configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_compose_dir }}/{{ item }}"
    mode: 0600
  with_items:
    - environment.sh
    - credentials.py
    - docker-compose.yml
    - nginx.conf
  notify:
    - update ca
    - restart container

- name: Render SECRET_KEY file
  copy:
    content: "{{ secret_key }}"
    dest: "{{ docker_compose_dir }}/SECRET_KEY"
    mode: 0600
  notify:
    - update ca
    - restart container

- name: Start the containers
  docker_compose:
    project_src: "{{ docker_compose_dir }}"
    restarted: false
  notify:
    - update ca
